dir_run: /projects/project_xxx/analysis/wgs
dir_data: /projects/project_xxx/data/wgs

libs_r:
  - /local/var/R/Rlibrary4/
  - /.condax/r-base/lib/R/library

species: homo_sapiens
genome: GRCh37

mapper: bwamem2

fasta: /doc/ref/GRCh37/fasta/GRCh37.primary_assembly.genome.fa
index_bwamem2: /doc/tool/mapper/bwamem2/GRCh37/gencode/GRCh37.primary_assembly.genome.fa

polymorphism_known:
  - /doc/db/gatkbundle/chr/dbsnp_138.b37.vcf.gz
  - /doc/db/gatkbundle/chr/1000G_phase1.indels.b37.vcf.gz
  - /doc/db/gatkbundle/chr/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
  - /doc/db/gatkbundle/chr/1000G_phase1.snps.high_confidence.b37.vcf.gz

dbsnp: /doc/db/gatkbundle/chr/dbsnp_138.b37.vcf.gz

suffixes_fastq:
  - "_R1.fq.gz"
  - "_R2.fq.gz"

clean_fq: true
run_fastqc: true
run_multiqc: false

penalty_mismatch: 3

cache_vep: /.vep
cache_snpeff: /doc/tool/annotator/snpeff
cache_annotsv: /doc/tool/annotator/annotsv
version_vep: 114
version_snpeff: 87
version_annotsv: v3.5
max_size_vep: 50000000
max_size_annotsv: 10000000
size_chunk: 300

min_reads: 3
min_coverage: 6
min_quality_mapping: 20
min_size: 50
min_dhffc: 0.7
max_dhbfc: 1.3

distance_sv:
  BND: 10
  DEL: 10
  INS: 10
  INV: 10
  DUP: 10
n_callers:
  BND: 3
  DEL: 2
  INS: 2
  INV: 2
  DUP: 2
consider_type:
  BND: false
  DEL: false
  INS: false
  INV: false
  DUP: false
consider_strand:
  BND: false
  DEL: false
  INS: false
  INV: false
  DUP: false
estimate_distance:
  BND: true
  DEL: true
  INS: true
  INV: true
  DUP: true

terms_relative: leuka?emia|blood|lymph|myelo|ha?ema|marrow|platel|thrombo|anemia|neutro

bed_exclude: /local/opt/gridss/example/chr/ENCFF001TDO.bed
jar_gridss: /local/opt/gridss/gridss-2.13.2-gridss-jar-with-dependencies.jar
